<?php
header( 'Content-type: text/plain' );
include 'config.php';
$id = $_GET['id'];
$company = mysqli_query( $config, 'SELECT * FROM company LIMIT 1' );
$companyrow = mysqli_fetch_assoc( $company );
$companyname = $companyrow['companyname'];
$address = $companyrow['companyaddress'];
$email = $companyrow['emailaddress'];
$phonenumber = $companyrow['phonenumbers'];
$website = $companyrow['website'];
$logo = $companyrow['logo'];
$count = "SELECT * FROM invoiceids WHERE id='$id'";
$qry = mysqli_query( $config, $count );
$row = mysqli_fetch_assoc( $qry );
$customername = $row['customername'];
$quotationdate = $row['quotedate'];
$expirydate = $row['expirydate'];
$deliverydate = $row['deliverydate'];
$heading = $row['description'];
$paymentterms = $row['paymentterms'];
$custqry = mysqli_query( $config, "SELECT * FROM customers WHERE Names='$customername'" );
$custrow = mysqli_fetch_assoc( $custqry );
$customeraddress = $custrow['Address'];
$customeremail = $custrow['EmailAddress'];
$customerphone = $custrow['PhoneNumber'];
//$line = $pdf->Ln( 4 );
//$customerdetails = $customername.',<br>.'.$customeraddress.'\n'.$customeremail.'\n'.$customerphone;
$br = '\n';
$customerdetails = 'test"'.$br.'"test2';
require( 'fpdf/fpdf.php' );
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont( 'Arial', 'B', 12 );
//title of the document
$pdf->Cell( 180, 8, 'INVOICE', 0, 0, R );
$pdf->Ln( 4 );
$pdf->SetFont( 'Arial', '', 8 );
$pdf->Cell( 180, 8, 'Ref.: '.$customername.'/'.$id, 0, 0, R );
$pdf->Ln( 4 );
$pdf->Cell( 180, 8, 'Quotation Date: '.$quotationdate, 0, 0, R );
$pdf->Ln( 4 );
$pdf->Cell( 180, 8, 'Expiry Date: '.$expirydate, 0, 0, R );
$pdf->Ln( 10 );
$pdf->Cell( 150, 8, 'From:', 0, 0, R );
$pdf->Ln( 4 );
$pdf->Cell( 162, 8, $companyname, 0, 0, R );
$pdf->Ln( 4 );
$pdf->Cell( 180, 8, $address, 0, 0, R );
$pdf->Ln( 4 );
$pdf->Cell( 174, 8, $email, 0, 0, R );
$pdf->Ln( 4 );
$pdf->Cell( 168, 8, 'Phone: '. $phonenumber, 0, 0, R );
$pdf->Ln( 4 );
$pdf->Image( $logo, 10, 6, 30 );
$pdf->Ln( 5 );
$pdf->Cell( 10, 8, 'To:', 0, 0, L );
$pdf->Ln( 4 );
$pdf->SetFillColor( 'cyan' );

$pdf->Cell( 10, 8, $customername, 0, 0, L, $fill );
$pdf->Ln( 4 );
$pdf->Cell( 10, 8, 'P.O Box '.$customeraddress, 0, 0, L, $fill );
$pdf->Ln( 4 );
$pdf->Cell( 10, 8, $customeremail, 0, 0, L, $fill );
$pdf->Ln( 4 );
$pdf->Cell( 10, 8, $customerphone, 0, 0, L, $fill );
//$pdf->Cell( 10, 8, $customerdetails, 0, 0, L, $fill );
$pdf->Ln( 10 );
$pdf->SetFont( 'Arial', B, 10 );
$pdf->Cell( 180, 8, $heading, 0, 0, C );
$pdf->Ln( 10 );
$pdf->SetFont( 'Arial', 'B', 8 );
$pdf->Cell( 60, 8, 'Description', 1, 0, L );
$pdf->Cell( 30, 8, 'Unit Cost', 1, 0, L );
$pdf->Cell( 30, 8, 'Quantity', 1, 0, L );
$pdf->Cell( 30, 8, 'Tax Amount', 1, 0, L );
$pdf->Cell( 30, 8, 'Total Cost', 1, 0, L );
$pdf->Ln( 8 );

$quotqry = mysqli_query( $config, "SELECT * FROM invoices WHERE invoiceid='$id'" );
$cummcost = 0;
$taxamount = 0;
while( $quoterow = mysqli_fetch_assoc( $quotqry ) ) {
    $item = $quoterow['item'];
    $unitcost = $quoterow['unitcost'];
    $quantity = $quoterow['quantity'];
    $tax = $quoterow['vat'];
    $totalcost = $quoterow['gross'];
    //$unitcost*$quantity;
    $cummcost = $cummcost+$totalcost;
    //$taxpercentage = $tax/100;
    //$taxcost = $taxpercentage*$totalcost;
    $taxamount = $taxamount+$tax;
    $pdf->SetFont( 'Arial', '', 8 );
    $pdf->Cell( 60, 6, $item, 1, 0, L );
    $pdf->Cell( 30, 6, number_format( $unitcost, 2 ), 1, 0, R );
    $pdf->Cell( 30, 6, $quantity, 1, 0, C );
    $pdf->Cell( 30, 6, $tax, 1, 0, C );
    $pdf->Cell( 30, 6, number_format( $totalcost, 2 ), 1, 0, R );
    $pdf->Ln( 6 );
}
$pdf->SetFont( 'Arial', B, 8 );
$pdf->Cell( 60, 6, '', 0, 0, L );
$pdf->Cell( 30, 6, '', 0, 0, R );
$pdf->Cell( 30, 6, '', 0, 0, C );
$pdf->Cell( 30, 6, 'Total Cost', 1, 0, C );
$pdf->Cell( 30, 6, number_format( $cummcost, 2 ), 1, 0, R );
$pdf->Ln( 6 );
$pdf->Cell( 60, 6, '', 0, 0, L );
$pdf->Cell( 30, 6, '', 0, 0, R );
$pdf->Cell( 30, 6, '', 0, 0, C );
$pdf->Cell( 30, 6, 'Tax Amount', 1, 0, C );
$pdf->Cell( 30, 6, number_format( $taxamount, 2 ), 1, 0, R );
$pdf->Ln( 6 );
$taxinclusive = $cummcost+$taxamount;
$pdf->SetFont( 'Arial', B, 8 );
$pdf->Cell( 60, 6, '', 0, 0, L );
$pdf->Cell( 30, 6, '', 0, 0, R );
$pdf->Cell( 30, 6, '', 0, 0, C );
$pdf->Cell( 30, 6, 'Cost(Incl.Tax)', 1, 0, C );
$pdf->Cell( 30, 6, number_format( $taxinclusive, 2 ), 1, 0, R );
$pdf->Ln( 6 );
$pdf->Cell( 50, 6, 'Planned Delivery Date: ', 0, 0, L );
$pdf->Ln( 6 );
$pdf->Cell( 50, 6, $deliverydate, 0, 0, L );
$pdf->Ln( 10 );
$pdf->Cell( 50, 6, 'Payment Terms: ', 0, 0, L );
$pdf->Ln( 6 );
$pdf->SetFont( 'Arial', '', 8 );
$pdf->Cell( 50, 6, $paymentterms, 0, 0, L );
//$pdf->Ln( 10 );
//$pdf->Cell( 50, 6, 'Written Acceptance, company stamp, signature and date: ', 0, 0, L );
//$pdf->Ln( 6 );
//$pdf->Cell( 80, 20, ' ', 1, 0, L );
//$pdf->SetX( 20 );
//$pdf->SetFont( 'Arial', '', 10 );
///$pdf->Cell( 40, 10, 'Click the Mark to get details', 0, 0, C, false );

$pdf->Output( 'D', 'Invoice'.$id.'.pdf', false );
header( 'location:invoices.php' );
?>